# Generated by Django 5.1.4 on 2024-12-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolastico", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materia",
            name="docente",
        ),
        migrations.AddField(
            model_name="materia",
            name="docentes",
            field=models.ManyToManyField(
                related_name="materias", to="escolastico.docente"
            ),
        ),
    ]
