# Generated by Django 5.1.4 on 2025-01-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolastico", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calificacion",
            name="parcial",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
